class ControllerTextConstants:

    LOGIN_SUCCESSFUL_MSG = "You are logged in, you will being redirected!"
    LOGIN_ERR = "Username or password incorrect!"
    REGISTER_SUCCESSFUL_MSG = "You are registered, you will being redirected!"
    REGISTER_ERR = "There is such account associated with this information!"
    PROFILE_RESET_USERNAME_EXIST_USER_ERR = "There is user associated with this username!"
    PROFILE_RESET_USERNAME_NULL_ERR = "Username cannot be null!"
    PROFILE_RESET_USERNAME_SUCCESSFUL = "Username is changed!"
    PROFILE_RESET_PASSWORD_LENGTH_ERR = "Password length must be 8 between 16"
    PROFILE_RESET_PASSWORD_SUCCESSFUL = "Password is changed!"
    PROFILE_RESET_EMAIL_EXIST_USER_ERR = "There is user associated with this email!"
    PROFILE_RESET_EMAIL_FORMAT_ERR = "Email address must be such example@domain.com"
    PROFILE_RESET_EMAIL_SUCCESSFUL = "Email is changed!"
    CHAT_CONTROL_NOT_FRIENDS = "You are not friends!"
    CHAT_DELETE_STREAM_SUCCESSFUL = "Stream is deleted!"
    FRIENDSHIP_USERNAME_ERR = "Username cannot be the same as your username!"
    FRIENDSHIP_NO_SUCH_USER_ERR = "There is no such user!"
    FRIENDSHIP_ALREADY_YOU_ARE_FRIENDS_ERR = "You are already friends!"
    FRIENDSHIP_ALREADY_SUCH_EXIST_REQUEST_ERR = "Already such exist friendship request!"
    FRIENDSHIP_REQUEST_SENT = "You sent a friendship request!"
    FRIENDSHIP_NO_SUCH_REQUEST_ERR = "No such incoming friendship request!"
    FRIENDSHIP_ACCEPTED_REQUEST = "You accepted the friendship request"
    FRIENDSHIP_IGNORED_REQUEST = "You ignored the friendship request!"
    FRIENDSHIP_NOT_FRIEND_ERR = "You are not friends!"
    FRIENDSHIP_REMOVED_FRIENDSHIP_LIST = "You removed from the list of friend!"
    NOTIFICATION_READ_NO_NOTIFICATION_ERR = "No notification to view!"
    NOTIFICATION_READ_NEW_NO_NOTIFICATION_ERR = "No new notification to view!"
    NOTIFICATION_DELETE_ALL_SUCCESSFUL = "Deleted all notifications!"
    NOTIFICATION_DELETE_ALL_ERR = "No notification to delete!"
    NOTIFICATION_DELETE_ONE_SUCCESSFUL = "Deleted notification!"
    NOTIFICATION_DELETE_ONE_ERR = "No such notification!"

class OtherConstants:
    
    DATE_FORMAT = "%d/%m/%Y %H:%M:%S"